### ISSUE TITLE
[학습] SQS 사양 확인.

### ISSUE THREAD

**Issue by gene-ss** [FileGround-CloudComputing/FileGround-Backend#1]
## GOAL
- SQS가 생각한 만큼 이상적으로 잘 작동하는지 검증 필요.

## TODO
- [x] SQS의 생성 및 삭제 시간 확인하기.  -> cli 혹은 sdk환경에서 체크 필요.

- [x] SQS의 태그에 ground id(일단은 임의로 세팅)를 달아줄 경우. 해당 아이디를 기반으로 서칭해서 생성 및 삭제 가능한지. -> 마찬가지로 cli 혹은 sdk환경에서 체크 필요.

- [x] 프론트에서 SQS의 메세지를 구독하면 딜레이는 어느 정도 인지 -> 간단한 목업 기반으로 부탁 드려요.

- [x] 프론트에서 SQS의 메세지를 여러 곳에서 동시에 받는다면 어떻게 되는건지 큐니까 한명만 받을 수 있는거 아닌가요?!?! 궁금 ㅋㅋ

- [x] 생산자 : SQS에서 특정 시간 간격으로 여러개의 만료 시간의 타임 스탬프 보내기 / 소비자 : 타임 스탬프 만료 됐는지 확인하고 삭제 필요 (삭제 과정 시뮬레이션)

**Comment by gene-ss** [comment]
## 문제
- SQS는 단일 소비자를 위한 큐이다. 그러므로 global queue의 용도로는 사용해도 되지만 ground queue의 용도로는 부적합 (https://stackoverflow.com/questions/53537413/using-amazon-sqs-for-multiple-consumers-receiving-the-same-message)
- 이런 경우에는 SNS가 더 적합. 단 보안이 취약(소비자 측에서 구독할 주제를 고를 수 있으므로)할 가능성이 있지만 배제. 그러나 SNS는 음... 테스트가 필요

## 다른 대안
- https://stackoverflow.com/questions/48474979/is-any-aws-service-suitable-for-sending-real-time-updates-to-browser

**Comment by sunwupark** [comment]
> ## 문제
> * SQS는 단일 소비자를 위한 큐이다. 그러므로 global queue의 용도로는 사용해도 되지만 ground queue의 용도로는 부적합 (https://stackoverflow.com/questions/53537413/using-amazon-sqs-for-multiple-consumers-receiving-the-same-message)
> * 이런 경우에는 SNS가 더 적합. 단 보안이 취약(소비자 측에서 구독할 주제를 고를 수 있으므로)할 가능성이 있지만 배제. 그러나 SNS는 음... 테스트가 필요
> 
> ## 다른 대안
> * https://stackoverflow.com/questions/48474979/is-any-aws-service-suitable-for-sending-real-time-updates-to-browser

sqs 가 왜 단일 소비자를 위한 큐 인가요..?

**Comment by gene-ss** [comment]
> > ## 문제
> > 
> > * SQS는 단일 소비자를 위한 큐이다. 그러므로 global queue의 용도로는 사용해도 되지만 ground queue의 용도로는 부적합 (https://stackoverflow.com/questions/53537413/using-amazon-sqs-for-multiple-consumers-receiving-the-same-message)
> > * 이런 경우에는 SNS가 더 적합. 단 보안이 취약(소비자 측에서 구독할 주제를 고를 수 있으므로)할 가능성이 있지만 배제. 그러나 SNS는 음... 테스트가 필요
> > 
> > ## 다른 대안
> > 
> > * https://stackoverflow.com/questions/48474979/is-any-aws-service-suitable-for-sending-real-time-updates-to-browser
> 
> sqs 가 왜 단일 소비자를 위한 큐 인가요..?

한 메세지를 다중 소비자가 동시에 얻을 수 없음.

**Comment by sunwupark** [comment]
> > > ## 문제
> > > 
> > > * SQS는 단일 소비자를 위한 큐이다. 그러므로 global queue의 용도로는 사용해도 되지만 ground queue의 용도로는 부적합 (https://stackoverflow.com/questions/53537413/using-amazon-sqs-for-multiple-consumers-receiving-the-same-message)
> > > * 이런 경우에는 SNS가 더 적합. 단 보안이 취약(소비자 측에서 구독할 주제를 고를 수 있으므로)할 가능성이 있지만 배제. 그러나 SNS는 음... 테스트가 필요
> > > 
> > > ## 다른 대안
> > > 
> > > * https://stackoverflow.com/questions/48474979/is-any-aws-service-suitable-for-sending-real-time-updates-to-browser
> > 
> > 
> > sqs 가 왜 단일 소비자를 위한 큐 인가요..?
> 
> 한 메세지를 다중 소비자가 동시에 얻을 수 없음.

아하 감사합니당!

**Comment by sunwupark** [comment]
##알면 좋은 정보##

https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-using-purge-queue.html

If you don't want to delete an Amazon SQS queue but need to delete all of the messages from it, purge the queue. The message deletion process takes up to 60 seconds. We recommend waiting for 60 seconds regardless of your queue's size.


https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html

When a consumer receives and processes a message from a queue, the message remains in the queue. Amazon SQS doesn't automatically delete the message. Because Amazon SQS is a distributed system, there's no guarantee that the consumer actually receives the message (for example, due to a connectivity issue, or due to an issue in the consumer application). Thus, the consumer must delete the message from the queue after receiving and processing it.

Amazon SQS sets a visibility timeout, a period of time during which Amazon SQS prevents other consumers from receiving and processing the message. The default visibility timeout for a message is 30 seconds. The minimum is 0 seconds. The maximum is 12 hours.

**Comment by gene-ss** [comment]
SQS를 소켓처럼 쓸 수 있을까?

사용자 한명 당 sqs 하나씩 배정하는 식으루

**Comment by sunwupark** [comment]
create_queue 하는데 걸린시간 : 0.12643sec
remove_queue 하는데 걸린시간: 0.18946sec

수정 코드
'
if __name__ == '__main__':
    #생성시간 측정
    start = time.time()
    create_queue('letsgo')
    end = time.time()
    print(f"{end - start:.5f} sec")


    #생선한 큐를 삭제하는데 걸리는 시간이다. 하지만 실제로 삭제되는대에는 더 걸릴 수 있다
    start = time.time()
    remove_queue(get_queue('letsgo'))
    end = time.time()
    print(f"{end - start:.5f} sec")
`

출처: 
https://github.com/awsdocs/aws-doc-sdk-examples/tree/main/python/example_code/sqs#code-examples

https://tech.cloud.nongshim.co.kr/2021/03/12/boto3%EA%B0%80-aws%EC%9D%98-%EC%9E%90%EA%B2%A9%EC%A6%9D%EB%AA%85credentials%EC%9D%84-%ED%99%95%EC%9D%B8%ED%95%98%EB%8A%94-%EC%88%9C%EC%84%9C-from-python/

**Comment by sunwupark** [comment]
> 

가능할것 같습니다! 돈만 있다면 ㅎㅎ

**Comment by gene-ss** [comment]
@sunwupark 어차피 메세지 개수 당 돈 받는거 아님? 100만개까지는 무료라 ㄱㅊ
혹시 큐 하나 생성시마다 과금이 되나요?
다른것도 얼른 해주세요.

**Comment by sunwupark** [comment]
SQS의 태그에 ground id(일단은 임의로 세팅)를 달아줄 경우. 해당 아이디를 기반으로 서칭해서 생성 및 삭제 가능한지. -> 마찬가지로 cli 혹은 sdk환경에서 체크 필요.

delete messages함수를 보면 한 큐에있는 messages를 꺼내서 message자체를 삭제하는데 send _messages함수를 보면 enumerate해서 임의로 id를 생성해서 message를 보내므로id를 기준으로 메세지를 받는다면 특정 메세지만 삭제 가능합니다. 잠시만요 코드도 올리겠습니다

**Comment by gene-ss** [comment]
@sunwupark 앗 메세지가 아니고 sqs 큐 이야기입니다. 메세지는 삭제할 일이 없어요!!

**Comment by sunwupark** [comment]
> 

아... 2시간동안 메세지 id삭제 찾고있었는데.. ㅠㅠ 이제봤네요.. 큐는 이름만 설정해놓으면 삭제할 수 있습니다

**Comment by sunwupark** [comment]
프론트에서 SQS의 메세지를 여러 곳에서 동시에 받는다면 어떻게 되는건지 큐니까 한명만 받을 수 있는거 아닌가요?!?! 궁금 ㅋㅋ

Amazon Simple Queue Service(SQS)는 분산 메시지 대기열 서비스이며, 여러 프로세스나 애플리케이션이 동시에 메시지를 수신할 수 있도록 설계되어 있습니다.

따라서 여러 프론트에서 SQS의 메시지를 동시에 수신하는 것은 문제가 되지 않습니다. SQS는 메시지를 받는 클라이언트들에게 메시지를 라운드 로빈 방식으로 분배하므로, 메시지를 동시에 받는 클라이언트들은 각자 다른 메시지를 처리할 수 있습니다.

그러나 여러 클라이언트가 동일한 메시지를 동시에 처리하려고 하는 경우 충돌이 발생할 수 있으므로 이에 대한 적절한 처리가 필요합니다.

**Comment by sunwupark** [comment]
대기열의 기본 (최소) 지연 시간은 0초입니다. 최대값은 15분

**Comment by gene-ss** [comment]
그래서 사람 하나 당 sqs를 하나씩 만들어주고
그라운드 이벤트 발생 시 
해당 sqs에 모두 메세지를 보내주는 방법으로 생각 했음
(그라운드 삭제 시 해당 sqs 모두 삭제해야하니 특정 태그로 찾아야하고)

이걸 너가 증명 중!!

**Comment by sunwupark** [comment]
그럼 인당 sqs가 하나씩 있고 그라운드가 만들어지면 각 sqs에 모든 메세지를 보내고 그라운드를 삭제하게 되면 그 인당 나누어준 sqs를 모두 삭제하는 건가요..?

**Comment by gene-ss** [comment]
예압~ 그래서 조사해본 내용으로 이 용도에 적합한가요?

**Comment by sunwupark** [comment]
인당 sqs 만들기 -> 가능합니다
각 sqs에 같은 메세지 보내기 -> 가능할것 같지만 좀더 해보겠습니다
그라운드 삭제시 인당 sqs도 삭제 -> 가능할것 같지만 좀더 해보겠습니다

결론 가능합니다. 다만 열심히 해보겠습니다.

**Comment by sunwupark** [comment]
![image](https://user-images.githubusercontent.com/52268188/228700637-4b6062d9-575f-4217-b3f7-5308fdd00762.png)

MessageRetentionPeriod를 1분으로 설정하고 time.sleep(61)로 61초후에 실행하니 이미 message가 삭제되어 가져오지 못하는 모습

**Comment by sunwupark** [comment]
즉 MessageRetentionPeriod만 잘 설정해주면 자동으로 시간이 지나면 삭제가 된다.

**Comment by sunwupark** [comment]
하지만 다른걸 실험해보니 queue자체가 message를 유지하는 시간이 60초인듯.. 하나 put하고 20초뒤에 put 하고 50초뒤에 get 했는데 못가져옴..

**Comment by sunwupark** [comment]
![image](https://user-images.githubusercontent.com/52268188/228712087-88ae0bce-3fc7-4f78-9be5-cf91ba7581fa.png)

이상하게 또 이렇게 하니깐 답이 잘 나옴

**Comment by gene-ss** [comment]
요정도면 테스트 잘한 것 같으니까 이슈 닫겠습니다. 새로 이슈 올릴테니 확인해주세요.
