### ISSUE TITLE
[학습] 파일 업로드 및 다운로드 

### ISSUE THREAD

**Issue by gene-ss** [FileGround-CloudComputing/FileGround-Backend#2]
## GOAL
- S3를 이용한 다중 파일 업로드 및 다운로드를 흔히 어떻게 처리하는지에 대해 학습한다.

## TODO

- [x] S3에 파일을 업로드하는 방식을 다른 곳에서는 어떻게 하는지 레퍼런스 찾아오기

- [x] 여러개의 파일을 업로드 할때에는 어떻게 처리하는지

- [x] 파일 명은 어떻게 하는지 

- [x] S3 파일 하나 하나에도 태그를 달 수 있는지 혹은 폴더를 써야하는지 (그라운드 삭제시 전부 삭제를 위해)

## Related Issue
우리의 경우 플러터(웹, 어플리케이션) 환경에서 다중 업로드 및 다중 다운로드가 빈번할 듯 한데, 이 경우 여러 파일 업로드 및 다운로드는 분리해야하는지?
- [x] #16

- [x] #17

**Comment by sangeun99** [comment]
- Python의 boto3 패키지를 이용해 aws s3에 접속하고 파일을 업로드할 수 있음(https://boto3.amazonaws.com/v1/documentation/api/latest/guide/s3-uploading-files.html)
_- AWS SDK, REST API 또는 AWS CLI를 사용 시 단일 PUT 작업으로 최대 5GB 크기의 단일 객체를 업로드할 수 있습니다. (https://docs.aws.amazon.com/ko_kr/AmazonS3/latest/userguide/upload-objects.html)_
- 파일 여러 개 업로드 시 list나 array에 넣어 처리하거나 그냥 반복문 사용한 예제 확인
- 숫자, 영어 대소문자, !, -, _등 객체 이름으로 사용 가능
_- 참고 : 객체 키 이름 규정 (https://docs.aws.amazon.com/ko_kr/AmazonS3/latest/userguide/object-keys.html)_
- 객체 업로드하며 객체마다 태그를 달 수 있음

* 사진 업로드 시 용량 제한, 개수 제한 논의하기

**Comment by gene-ss** [comment]
잘 확인했습니다.
- 혹시 일반적인 프론트-백엔드 환경에서 프론트 업로드 및 다운로드는 어떻게 처리하는지 확인해주실 수 있나요?
- 그리고 파일 다운로드 및 업로드에 대한 명세서 작성 부탁드립니다.
- 명세서 작성의 경우 이슈 2가지로 분리했습니다. 담당자 설정했으니 내용 채워주세요~

**Comment by sangeun99** [comment]
명세서 작성의 경우 (업로드) post /photo/:photo.id, (다운로드) get /photo/:photo.id 이런 식으로 작성하면 되나요? 자세한 설계가 필요할까요?

**Comment by choi5798** [comment]
네 기존에 작성되어있는 폼 참고하셔서 작성하세요
요청시와 응답시에 어떤 값이 전달될지 예시 데이터를 함께 작성해주시면 감사하겠습니다
URL의 경우에는 어떤 그라운드에서 파일을 처리하는지 모르니 그라운드 id 추가 부탁드립니다

**Comment by gene-ss** [comment]
@choi5798 @sangeun99 
업로드 하는 시점에서는 포토의 아이디를 알 수 없습니다. post /photo로 해주세요.

**Comment by choi5798** [comment]
@bluejoyq 그 점을 간과했네요! 지적 감사합니다

**Comment by sangeun99** [comment]
@bluejoyq 넵! 맞춰서 작성하겠습니다!

**Comment by sangeun99** [comment]
S3 객체 업로드 예시
https://github.com/meech-ward/s3-get-put-and-delete
여러 개의 파일 업로드 지원해야 하기 때문에, upload.single 대신 upload.array 이용해야 함

**Comment by gene-ss** [comment]
@sangeun99 제 생각으론 업로드를 서버를 거쳐서 하는게 아니라 서버에 요청을 보내면 id와 업로드 url을 생성해서 보내주는 겁니다. 이게 가능할까요? -> 어차피 람다가 업로드 완료시 디비 갱신하기에 id만 중복이 안되면 괜찮을 것 같은데.

**Comment by sangeun99** [comment]
@bluejoyq pre-signed url을 이용해서 s3을 업로드하는 방법이 있네요! 이 방법으로 하면 서버를 거치지 않고 가능합니다! 이 부분 말씀하신 거 맞을까요?
https://velog.io/@seeh_h/AWS-S3-presignedURL%EC%9D%84-%EC%9D%B4%EC%9A%A9%ED%95%B4%EC%84%9C-image-Upload-%ED%95%98%EA%B8%B0-qvqo81gk

**Comment by gene-ss** [comment]
@sangeun99 네 맞습니다. 그런데 업로드가 실패되면 해당 url은 자동으로 만료되는 건가요?

**Comment by sangeun99** [comment]
@bluejoyq 아뇨 url은 유효시간 만료까지 유효합니다. 유효시간 만료까지는 같은 url로 이미지를 여러번 업로드하는 것도 가능합니다.
