### ISSUE TITLE
[설계] 기획 내용 기반으로 API 설계하기

### ISSUE THREAD

**Issue by gene-ss** [FileGround-CloudComputing/FileGround-Backend#4]
## GOAL
- 람다가 할 가능성이 있다는 부분을 제외하고 엔티티 및 API 설계하기
- 파일 업로드 및 다운로드는 제외했습니다.

### 인증
- [x] 회원가입

- [x] 리프레쉬 토큰 갱신(로그인)

- [x] 액세스 토큰 갱신

- [x] 로그아웃

### 유저
- [x] 유저 정보 읽어오기

~~- [ ] 인증~~

~~- [ ] 내 그라운드 목록 가져오기~~

### 그라운드
- [x] 그라운드 좌표 검증 (링크 검증이랑 비슷한 맥락)

- [x] 그라운드 생성

- [x] 그라운드 사진 조회

- [x] 그라운드 삭제

~~- [ ] 링크 및 QR 코드 생성 (사실 QR코드만 생성하면 되긴함) -> 이건 프론트에서 처리해야하나?~~

**Comment by choi5798** [comment]
오키

**Comment by gene-ss** [comment]
## DB 설계 개선 사항
- db 설계 유저에 accessToken 빠졌어요.
- image 업로더 혹은 태그에 대한 정보가 빠진 것 같아요. (for filtering)
- image url보다는 src가 맞을듯.
- image thumnail 빠짐
- date type 통일 부탁
- ground의 current_people은 리스트여야 하는거 아님?
- 각 항목에 대한 설명도 간단하게 달아주세요.

## 기타
- image보다는 photo가 나을 듯. -> image는 프레임워크에서 중복되는 항목이 존재

**Comment by gene-ss** [comment]
안녕하세요, Access Token과 Refresh Token 전략에 대한 API 명세서 작성 방법에 대해 안내해드리겠습니다.

엔드포인트

Access Token 발급 요청: POST /oauth/token
Access Token 갱신 요청: POST /oauth/token
Access Token 만료 확인 요청: GET /oauth/token/expiry
Refresh Token 만료 확인 요청: GET /oauth/refresh_token/expiry
요청과 응답

Access Token 발급 요청:
요청 바디: grant_type=client_credentials&client_id=<your_client_id>&client_secret=<your_client_secret>
응답 바디: {"access_token": "<your_access_token>", "expires_in": 3600, "token_type": "Bearer", "refresh_token": "<your_refresh_token>"}
Access Token 갱신 요청:
요청 바디: grant_type=refresh_token&client_id=<your_client_id>&client_secret=<your_client_secret>&refresh_token=<your_refresh_token>
응답 바디: {"access_token": "<your_new_access_token>", "expires_in": 3600, "token_type": "Bearer", "refresh_token": "<your_new_refresh_token>"}
Access Token 만료 확인 요청:
요청 바디: Authorization: Bearer <your_access_token>
응답 바디: {"expired": false}
Refresh Token 만료 확인 요청:
요청 바디: Authorization: Bearer <your_refresh_token>
응답 바디: {"expired": false}
보안

요청과 응답 모두 HTTPS 프로토콜을 사용해야 합니다.
Client ID와 Client Secret은 안전한 곳에 보관해야 합니다.
Access Token과 Refresh Token은 만료 기간을 지정하여 발급해야 합니다.
예외 처리

Access Token 발급 요청과 갱신 요청에서 인증 실패시, 401 Unauthorized 에러를 반환합니다.
Access Token 만료 확인 요청과 Refresh Token 만료 확인 요청에서 만료된 토큰일 경우, {"expired": true}와 함께 401 Unauthorized 에러를 반환합니다.
이러한 방법으로 Access Token과 Refresh Token 전략에 대한 API 명세서를 작성할 수 있습니다. 필요에 따라 API 명세서에 추가 정보를 포함시켜 보다 자세한 API 사용 방법을 안내할 수 있습니다.

**Comment by choi5798** [comment]
> ## DB 설계 개선 사항
> * db 설계 유저에 accessToken 빠졌어요.
> * image 업로더 혹은 태그에 대한 정보가 빠진 것 같아요. (for filtering)
> * image url보다는 src가 맞을듯.
> * image thumnail 빠짐
> * date type 통일 부탁
> * ground의 current_people은 리스트여야 하는거 아님?
> * 각 항목에 대한 설명도 간단하게 달아주세요.
> 
> ## 기타
> * image보다는 photo가 나을 듯. -> image는 프레임워크에서 중복되는 항목이 존재

current_people 이 단순히 링크에 접속한 사람 수가 아니가 누가 들어왔는지 알게 하려면 리스트가 맞을 것 같습니다
그 이외 DB 설계 개선 사항들은 반영했습니다!

**Comment by gene-ss** [comment]
![image](https://user-images.githubusercontent.com/42014299/227773509-d6fce811-3049-4ead-adff-1ab4ab3d8e9b.png)

**Comment by choi5798** [comment]
## GOAL
- 람다가 할 가능성이 있다는 부분을 제외하고 API 명세서 작성하기

## TODO
### 인증
- [ ] 회원가입

- [ ] 리프레쉬 토큰 갱신(로그인)

- [ ] 액세스 토큰 갱신

- [ ] 로그아웃

### 유저
- [ ] 유저 정보 읽어오기

### 그라운드
- [ ] 그라운드 좌표 검증 (링크 검증이랑 비슷한 맥락)

- [ ] 그라운드 생성

- [ ] 그라운드 사진 조회

- [ ] 그라운드 삭제
